### ISSUE TITLE
PHP Fatal error:  Allowed memory size of 67108864 bytes exhausted

### ISSUE THREAD

**Issue by vyleon** [blueimp/jQuery-File-Upload#3713] opened 2021-02-14 00:05 UTC
After upgrading to php 8.0.2 from 7.4, UploadHander.php started throwing an error on attempted uploads as follows:

FastCGI sent in stderr: "PHP message: PHP Fatal error: Allowed memory size of 67108864 bytes exhausted (tried to allocate 32768 bytes) in /var/www/vhosts/xxx/httpdocs/xxx/xxx/xxx/UploadHander.php on line 617"

As previously, the script sets:
set_time_limit(180);
ini_set("memory_limit", "64M");
ini_set('post_max_size', '60M');
ini_set('upload_max_filesize', '60M');

Perhaps a bug more with the new PHP 8 than the UploadHandler script, but still raising as a possible issue?

**Comment by blueimp** [comment] 2021-09-25 03:04
I've release a new version of the Apache PHP demo and could not reproduce an issue with PHP 8.
Closing as non-reproducible for now, but feel free to comment if you can confirm that this is still an issue.

**Closed by blueimp** 2021-09-25 03:04 UTC
