### ISSUE TITLE
Not upload image.

### ISSUE THREAD

**Issue by kvinkinamoto** [blueimp/jQuery-File-Upload#3674] opened 2020-09-01 19:28 UTC
![covid_0109](https://user-images.githubusercontent.com/1387047/91897057-65808500-eca2-11ea-89df-2f0dca922c0b.jpg)

**Comment by kvinkinamoto** [comment] 2020-09-01 19:30
when I try to load this image nothing happens. The rest are loaded normally

**Comment by blueimp** [comment] 2020-09-06 05:34
Thanks for your report @kvinkinamoto.

Can you reproduce this issue on the [demo](https://blueimp.github.io/jQuery-File-Upload/)? (I was not able to reproduce this with Chrome on macOS).

If this issue only happens in your own setup, you might wanna check if you have the latest version of the [JavaScript-Load-Image](https://github.com/blueimp/JavaScript-Load-Image) dependency.

**Comment by blueimp** [comment] 2020-10-19 14:38
Since there was no answer in a month, closing this as solved.

**Closed by blueimp** 2020-10-19 14:38 UTC
