### ISSUE TITLE
Firefox crash when uploading multiple files

### ISSUE THREAD

**Issue by anupmsinhal** [blueimp/jQuery-File-Upload#3301] opened 2014-08-16 11:18 UTC
I use firefox 32.0 and when I am trying to upload more than 15 files of approximately 5 mb each the browser is crashing. 

The same is working fine in Chrome.

In Opera, the plugin always uploads one or two files less, but does not crash (Sometimes uploads 13 files, sometimes 14 files. Its weird)

**Comment by blueimp** [comment] 2020-02-17 14:30
Cannot reproduce this in Firefox 73 - closing as obsolete.

**Closed by blueimp** 2020-02-17 14:30 UTC
