### ISSUE TITLE
Image is not uploading due to XMP data. 

### ISSUE THREAD

**Issue by BhargaviVenkatesh** [blueimp/jQuery-File-Upload#3651] opened 2020-06-04 10:09 UTC
Please suggest how to remove it through the code.
![pictureupload](https://user-images.githubusercontent.com/57741761/83744224-6bea6b00-a679-11ea-924f-40a1f920c215.png)

**Comment by Goldenflamer** [comment] 2020-06-06 20:29
@BhargaviVenkatesh 

I have the same problem this seems to be a bug in code introduced lately.

JPG is no longer working but PNG is still working fine.

**Comment by Goldenflamer** [comment] 2020-06-08 12:32
My solution was to roll back the non locally stored js files via waybackmachine.
Could be a problem in the template, some js files are pulled from github others are stored locally, I guess that is where the problem comes from.

**Comment by blueimp** [comment] 2020-06-08 14:03
Thanks for your report, @BhargaviVenkatesh  and @Goldenflamer.

Could you provide a sample image with XMP data that does not work?

And can you reproduce this issue on the [demo site](https://blueimp.github.io/jQuery-File-Upload/)?

If not, this is probably due to an outdated [blueimp-load-image](https://github.com/blueimp/JavaScript-Load-Image) dependency.

If you're installing via NPM, you should have have a version of this dependency that works with the jQuery File Upload version installed.
Otherwise, you could also update both libraries to their latest version.

**Comment by listprocessor** [comment] 2020-06-09 13:50
Same Problem for me. A few days (weeks) ago all my sites worked with jpg. Now none of my sites is able to upload jpg Images. (PNG work fine thanks to @BhargaviVenkatesh

**Comment by blueimp** [comment] 2020-06-09 14:03
Hi @listprocessor, it would be nice if you could also provide answers to the questions I posted above:

Could you provide a sample image with XMP data that does not work?

And can you reproduce this issue on the [demo site](https://blueimp.github.io/jQuery-File-Upload/)?

**Comment by listprocessor** [comment] 2020-06-09 14:09
I tested it with one of the photos that  failed for me on your demo site and your demo site worked.

Unfortunately I haven't got any jpg file that works on any of my sites.

**Comment by blueimp** [comment] 2020-06-09 14:18
Thanks for your reply.

Are you using the latest versions of both jQuery File Upload and [JavaScript-Load-Image](https://github.com/blueimp/JavaScript-Load-Image) (which is the dependency used to load image files)?

Note: If you install jQuery File Upload  via
```
npm install blueimp-file-upload
```
you should have a compatible `blueimp-load-image` dependency in the `./node_modules/blueimp-load-image` directory.

**Comment by listprocessor** [comment] 2020-06-09 14:32
No I use sn old one.  According to blueimp-file-upload.jquery.json:

"name": "blueimp-file-upload",
  "version": "9.8.0",

It worked great for several years now and for some unknown reason it does not work anymore. I did not change any of my sites and all use the same version.

**Comment by blueimp** [comment] 2020-06-09 14:37
OK, please check how you are including the [JavaScript-Load-Image](https://github.com/blueimp/JavaScript-Load-Image) dependency.
You might be including them straight from GitHub like this, which is not recommended:

https://github.com/blueimp/jQuery-File-Upload/blob/1c84ab1ed9e7547701222484e4e770bfeaa7862e/index.html#L304

From the [setup](https://github.com/blueimp/jQuery-File-Upload/wiki/Setup) guide
> Although the demo implementations contained in this repository include source files from remote servers, it is recommended to download all dependencies and upload them to your own server.
> This excludes script files hosted on Google's Content Delivery Network, which is a more reliable source than GitHub demo pages.

**Comment by listprocessor** [comment] 2020-06-10 08:59
Thanks @blueimp . as always its an RTFM case :-). That's it! I managed to download an older Version that worked. 
I still have to upgrade to your latest version but that will take some time. 
Thank you so much for your work!

**Comment by blueimp** [comment] 2020-06-10 10:09
You're welcome. :)

@BhargaviVenkatesh and @Goldenflamer:
I assume that this is a similar issue and we can close this?

**Comment by blueimp** [comment] 2020-06-20 09:31
Closing this as resolved.

**Closed by blueimp** 2020-06-20 09:31 UTC
