### ISSUE TITLE
PHP Notice:  Trying to access array offset on value of type null in UploadHandler.php on line 497 php 7.4

### ISSUE THREAD

**Issue by cfconsultancy** [blueimp/jQuery-File-Upload#3557] opened 2020-02-16 09:48 UTC
With php 7.4 the following notice appear and the upload fails

PHP Notice:  Trying to access array offset on value of type null in UploadHandler.php on line 497

**Comment by blueimp** [comment] 2020-02-16 10:37
This is a duplicate of #3534.
That issue has been closed in a2a6722, so you probably want to upgrade [UploadHandler.php](https://github.com/blueimp/jQuery-File-Upload/blob/master/server/php/UploadHandler.php) to the latest version.

**Closed by blueimp** 2020-02-16 10:37 UTC
