### ISSUE TITLE
Upload is not working (Safari iOS8 GM)

### ISSUE THREAD

**Issue by usefksa** [blueimp/jQuery-File-Upload#3351] opened 2014-09-14 14:45 UTC
I download the latest version of iOS8, I noticed the script is not working. I can choose the image but after hitting start upload, the app do not upload the image.

I connected my iPhone to MAC , I noticed the following Javascript error displayed after choosing the image and before clicking  'start upload'
load-image.min.js:1:11575
[Log] FileError (load-image.min.js, line 1)
code: 4
**proto**: FileErrorPrototype
ABORT_ERR: 3
ENCODING_ERR: 5
INVALID_MODIFICATION_ERR: 9
INVALID_STATE_ERR: 7
NOT_FOUND_ERR: 1
NOT_READABLE_ERR: 4
NO_MODIFICATION_ALLOWED_ERR: 6
PATH_EXISTS_ERR: 12
QUOTA_EXCEEDED_ERR: 10
SECURITY_ERR: 2
SYNTAX_ERR: 8
TYPE_MISMATCH_ERR: 11
constructor: FileErrorConstructor
**proto**: Object

The image format is jpg and the size is 1.76
I test on iOS 7, it is working fine.

**Comment by blueimp** [comment] 2020-02-17 13:56
Closing this as iOS8 is rather old and I never got around to address this.

**Closed by blueimp** 2020-02-17 13:56 UTC

**Comment by blueimp** [comment] 2020-02-17 14:03
Duplicate of #3316
