### ISSUE TITLE
PNG file resize fail

### ISSUE THREAD

**Issue by clickmeplz** [blueimp/jQuery-File-Upload#3685] opened 2020-10-28 06:52 UTC
It can not resize PNG files anymore. Please investigate

**Comment by blueimp** [comment] 2020-10-28 07:18
Hi @clickmeplz,

Unfortunately I cannot reproduce any issues with PNG resizing.

Can you reproduce this issue on the [demo](https://blueimp.github.io/jQuery-File-Upload/)?

e.g. with the following large PNG image, it should be rescaled on client-side to a smaller version (both for the preview and the file to be uploaded):
https://upload.wikimedia.org/wikipedia/commons/3/35/Fond_d%27%C3%A9cran_de_Debian.png

**Comment by clickmeplz** [comment] 2020-10-28 08:16
Sure... Here it is
![1](https://user-images.githubusercontent.com/23030626/97409513-fa0a0b00-1912-11eb-93fa-5b91edf21c93.png)

**Comment by blueimp** [comment] 2020-10-28 08:19
There's no guarantee that the resized file will be smaller in bytes.

However your issue mentioned that you're unable to resize at all and it seems this is not the case on the demo?

**Comment by clickmeplz** [comment] 2020-10-28 08:29
Sorry! but i don't understand your mean?
I downloaded your link to client. It is 748K (2560 * 1600).
Then i uploaded at demo. It will be 922K (172 * 1080).
If i changed it to .jpg file everything is OK. My local jpg will be 243 K but when i uploaded at demo it changed to 101K, which means demo works fine with jpg.
![1](https://user-images.githubusercontent.com/23030626/97410943-ea8bc180-1914-11eb-8a5a-06bbbc193b0b.png)

**Comment by blueimp** [comment] 2020-10-28 09:04
If you want to make sure resized images are smaller in file size, you can provide the `imageType` and `imageQuality` options:
```js
$('#fileupload').fileupload({
    imageType: 'image/jpeg',
    imageQuality: 0.5
});
```
See also:
https://github.com/blueimp/jQuery-File-Upload/wiki/Options#imagetype
https://github.com/blueimp/jQuery-File-Upload/wiki/Options#imagequality
https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/toBlob

You can even apply these options to the demo, by executing the following in the browser console:
```js
$('#fileupload').fileupload('option', {
    imageType: 'image/jpeg',
    imageQuality: 0.5
});
```

Since saving canvas images as PNGs does not support the quality option, you have to use JPEG (or WEBP) for file size savings.

For PNGs, the browser uses default options which might create bigger file sizes, despite smaller dimensions.

**Comment by clickmeplz** [comment] 2020-10-28 09:45
Thank you to explain completely. Perhaps i have to restrict users only to only JPEG and GIF, until i find a solution, because i am loosing my web storage very fast, because of PNG files. Thank you.

**Comment by blueimp** [comment] 2020-10-28 09:50
You're welcome.
If you wanna protect your web storage limits, I would recommend you to limit the max file size and max number of files to upload on the server-side.

**Comment by clickmeplz** [comment] 2020-10-28 10:21
I appreciate your recommend.
![1](https://user-images.githubusercontent.com/23030626/97423558-a1dc0480-1924-11eb-94a6-7d7555b1c416.png)

**Comment by blueimp** [comment] 2020-10-28 10:22
Alright, sounds like we can close this issue?

**Comment by clickmeplz** [comment] 2020-10-28 10:38
Sure, thank you so much

**Closed** 2020-10-28 10:39 UTC
