### ISSUE TITLE
demo code show error when upload some small jpg files

### ISSUE THREAD

**Issue by hexins** [blueimp/jQuery-File-Upload#3708] opened 2021-01-21 11:07 UTC
the demo code show "SyntaxError: Unexpected token < in JSON at position 0" for some small jpeg files, no idea where the error message is, jpeg files are attached. 
![lf](https://user-images.githubusercontent.com/27618008/105342735-ae1de800-5c1b-11eb-88a8-3d11d3d04e5d.jpg)
![righ](https://user-images.githubusercontent.com/27618008/105342798-c55cd580-5c1b-11eb-92fd-f467ea455896.jpg)

**Comment by blueimp** [comment] 2021-09-25 02:59
Hi @hexins, first thanks for providing sample files, that's very helpful.
Unfortunately I could not reproduce this on the [public demo](https://blueimp.github.io/jQuery-File-Upload/), nor with the included PHP demo.
I'll close this for now as not an issue with the library, but feel free to provide further comments on this ticket.

**Comment by blueimp** [comment] 2021-09-25 03:00
An additional note: You probably want to look into the Browser network panel, as this error probably signifies that the server response is not the expected JSON response, but likely an error message.

**Closed by blueimp** 2021-09-25 02:59 UTC
