### ISSUE TITLE
Clientside Resize and ImageOrientation not working together. If so how?

### ISSUE THREAD

**Issue by fatihtas** [blueimp/jQuery-File-Upload#3641] opened 2020-05-09 15:41 UTC
Hi,
My setup is: user uploads a picture from their phone on mobile or Desktop browser. Later, I upload max 1600px resized picture to S3. and then, I use lambda function to generate different versions etc. 

However problem is: when setting
` imageOrientation: true `
` disableImageMetaDataSave: true`
 
Exif Orientation 6 and 8 values seem reverse. other orientations working well.  

The thing is picture seem proper on both iphone and Macbook. (exif data is either 6 or 8, mac and iphone both delivers proper orientation to its users. ) 
However when uploaded to a website under these settings, these two picture both seem reverse (like Exif orientation value of 3 - 180 degree reverse) 
++ Very interestingly this setup works like this in Opera browser. However when same page looked at in Safari, Chrome or Firefox. Pictures don't seemed oriented when using fancybox gallery. However if we open the picture in separate window they look good (except for value 6 and 8)

Someone mentions in another closed issue that  `disableImageResize: false` causing similar problem. But i don't see why. And of course people should be able to use both resizing and true orientation features at the same time. 
When I set to `disableImageResize: true` they all look fine on Opera. [See screenshot](https://www.dropbox.com/s/jqwqkth267ak8vj/Screen%20Shot%202020-05-09%20at%206.36.16%20PM.png?dl=0) 
Same page looks on Safari|Chrome|Firefox very different though! [See screenshot for them](https://www.dropbox.com/s/l9orimiire6h26u/Screen%20Shot%202020-05-09%20at%206.37.03%20PM.png?dl=0)

I tried,` disableImageMetaDataLoad: true` option set to true at last, and that yielded proper orientation for all browsers including exif-6,8. However that setup is not working on mobile devices, due to its default orientation value of 1 is sideways indeed (like Exif value 6). 

and again very interestingly, same pictures all look good when I try your demo. So obviously I am doing things wrong at some point. 

I use rails, and s3_direct_upload btw. It makes most sense for me to truly orient and resize pictures on the client side. Because some original pictures are like ~20MB whereas resized versions are < 1MB so making it cheaper to keep on s3. 
Another thing I want to try is, not depending on` imageOrientation: true ` setting and manually  flip and angle images after or before resizing. Yet I couldn't find any resource on that. 

So, even if this fix is not possible via settings, I appreciate If you can help me with providing samples etc. (i am beginner in coding.)

Thanks a lot

**Comment by blueimp** [comment] 2020-05-10 18:16
Thanks for your report @fatihtas.
Since this is not reproducible on the demo, I'm closing this tentatively as not an issue in the library (see also #2190).

However, feel free to continue commenting on this ticket and I'll also try to provide some pointers.

Did you update to the latest version of this library?
There have been updates to how browsers handle automatic image orientation, which required changes in both this library as well as the dependency [blueimp-load-image](https://github.com/blueimp/JavaScript-Load-Image).

It should be perfectly fine to set both `imageOrientation: true` and `disableImageMetaDataSave: true`. The latter will simply lead to images being sent to the server without their original meta data, as image scaling via canvas does not preserve any meta data.

**Closed by blueimp** 2020-05-10 18:16 UTC

**Comment by fatihtas** [comment] 2020-05-10 21:40
Thanks @blueimp for your answer. 
I am using this on Rails-4, through s3_direct_upload gem that I customized, so I am sure I am not using the latest version. 

One interesting thing I noticed meanwhile is that. Your setup guide worked fine on Safari, Chrome and Firefox, but not on Opera this time under the settings I provided below. (I use Opera 90% of the time on my computer, so I was trying to optimize things first on Opera later checking other browsers.)
So anyone out there having same problem, can save a little time by applying this. 

here is my new settings: 

```
imageOrientation: true 
disableImageMetaDataSave: true
disableImageResize: false
imageForceResize: true
image_library: 0
```
So considering Opera has less market share I am leaving this as it is. However your demo works well on any browser and mobile/desktop device I have tried. So there is definitely a glitch out there. 
My opera version is Version:68.0.3618.91

I have also tried to determine `true` and `false` values based on which browser page loaded in. Yet it is not reliable and those methods constantly changing, plus also forces me to non-resized images.  

Thanks.

**Comment by blueimp** [comment] 2020-05-11 05:59
In this case you probably wanna nudge the maintainer of the `s3_direct_upload` gem to update the dependencies.

Opera is using the Chromium Blink engine, so I'm surprised to hear you have different results with this browser.

Can you explain in detail what exactly does not work following the setup guide?
